set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/global_bottom_nav_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/global_top_status_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/home_reservoir_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/home_sensor_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/home_status_row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/irrigation_edit_settings_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/irrigation_overview_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/irrigation_pump_cycle_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/irrigation_summary_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/irrigation_window_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/led_edit_settings_button_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/led_preset_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/led_schedule_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/mini_trend_chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/sensors_screen_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_8_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_9_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_10_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_11_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_15_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_26_data.c
  ${CMAKE_CURRENT_LIST_DIR}/gl_towers_embedded_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/gl_towers_embedded_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_gl_towers_logo_1_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_home_irrigation_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_home_light_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_home_pump_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_clock_16px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_clock_24px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_drop_16px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_drop_24px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_drop_silhouette_16px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_drop_silhouette_24px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_germination_16px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_germination_24px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_irrigation_pump_24px_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_nav_home_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_nav_irrigation_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_nav_light_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_nav_sensors_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_nav_settings_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_top_status_bar_no_wifi_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_top_status_bar_wifi_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_alerts_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_calibration_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_diagnostics_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_ec_calibration_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_irrigation_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_led_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_load_cell_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_ota_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_pairing_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_ph_calibration_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_saver_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_sensors_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_wifi_gen.c)